### Crypto Trading Bot Config ###

#################### PERCENTAGE TRADING STRATEGY ######################
server:
  port: 8080
exchange:
  apiKey: HTqza54XTX09uBANVQOvMO78N478MhDxLbEiBfSRR8Yc7MBIlXGxG2cwK4Ok3KvI
  secretKey: vOZJYqQrYjgwSL5EDUxLYTv7Gh8nQvRqX5IefmnySqSAUdVvgOTfTe6HJsO9tvTY
  useTestnet: false
mongoDb:
  uri: mongodb://localhost:27017
  database: ctb