# testnet configuration

exchange:
  apiKey: fkAHgTpxMVBWXueZfAyYK2NnR4SZdTNPR45mlJivVg4dNEnoWSbODTUQHDkiNjN6
  secretKey: 4yFKwURuMG7onlVoqFeV4Fz3I7ZNcNFMmDTRrlUk45IbbudFEWJtXAQGhqJEJtPg
  useTestnet: true
mongoDb:
  uri: mongodb://localhost:27017
  database: ctb-testnet
strategy:
  type: DEMO_STRATEGY
  config:
    buyThreshold: '2.5'
    sellThreshold: '2.5'
    stopLossThreshold: '5'
    missProfitThreshold: '5'