### Crypto Trading Bot Simulation Config ###

######################## DEMO TRADING STRATEGY ########################
#exchange:
#  initialBalances:
#    ETH: '2000'
#    BTC: '100'
#  priceFilepaths:
#    ETHUSDT: /home/stacksmasher/crypto-prices/Gemini_ETHUSD_d_2021.csv
#    BTCUSDT: /home/stacksmasher/crypto-prices/Gemini_BTCUSD_d_2021.csv
#  priceDelay: '100'
#mongoDb:
#  uri: mongodb://localhost:27017
#  database: ctb-simulation
#strategy:
#  type: DEMO_TRADING_STRATEGY
#  config:
#    buyThreshold: '10'
#    sellThreshold: '10'
#    stopLossThreshold: '25'
#    missProfitThreshold: '25'

#################### PERCENTAGE TRADING STRATEGY ######################
exchange:
  initialBalances:
    ETH: '10'
    BTC: '1'
    USDT: '200000'
  priceFilepaths:
    ETHUSDT: /home/stacksmasher/crypto-prices/Gemini_ETHUSD_d_2021.csv
    BTCUSDT: /home/stacksmasher/crypto-prices/Gemini_BTCUSD_d_2021.csv
  priceDelay: '100'
mongoDb:
  uri: mongodb://localhost:27017
  database: ctb-simulation
strategy:
  type: PERCENTAGE_TRADING_STRATEGY
  config:
    buyPercentage: '10'
    sellPercentage: '10'
    buyAmountPercentage: '20'
    sellAmountPercentage: '20'