### Crypto Trading Bot Testnet Config ###

######################## DEMO TRADING STRATEGY ########################
#exchange:
#  apiKey: fkAHgTpxMVBWXueZfAyYK2NnR4SZdTNPR45mlJivVg4dNEnoWSbODTUQHDkiNjN6
#  secretKey: 4yFKwURuMG7onlVoqFeV4Fz3I7ZNcNFMmDTRrlUk45IbbudFEWJtXAQGhqJEJtPg
#  useTestnet: true
#mongoDb:
#  uri: mongodb://localhost:27017
#  database: ctb-testnet

#################### PERCENTAGE TRADING STRATEGY ######################
exchange:
  apiKey: fkAHgTpxMVBWXueZfAyYK2NnR4SZdTNPR45mlJivVg4dNEnoWSbODTUQHDkiNjN6
  secretKey: 4yFKwURuMG7onlVoqFeV4Fz3I7ZNcNFMmDTRrlUk45IbbudFEWJtXAQGhqJEJtPg
  useTestnet: true
mongoDb:
  uri: mongodb://localhost:27017
  database: ctb-testnet