
# testnet configuration

exchange:
  apiKey: HTqza54XTX09uBANVQOvMO78N478MhDxLbEiBfSRR8Yc7MBIlXGxG2cwK4Ok3KvI
  secretKey: vOZJYqQrYjgwSL5EDUxLYTv7Gh8nQvRqX5IefmnySqSAUdVvgOTfTe6HJsO9tvTY
  useTestnet: false
mongoDb:
  uri: mongodb://localhost:27017
  database: ctb
strategy:
  type: DEMO_TRADING_STRATEGY
  config:
    buyThreshold: '5'
    sellThreshold: '5'
    stopLossThreshold: '10'
    missProfitThreshold: '10'